name: Eve-Ent

options:
  bundleIdPrefix: com.vstu.Eve-Ent
  deploymentTarget:
    iOS: "13.2"
  transitivelyLinkDependencies: true
  developmentLanguage: en
  createIntermediateGroups: true
  generateEmptyDirectories: true

targets:
  Eve-Ent:
    type: application
    platform: iOS
    sources:
      - path: Sources/Eve-Ent
      - path: Sources/Eve-Ent/Generated/L10n.swift
        optional: true
      - path: Sources/Eve-Ent/Generated/Assets.swift
        optional: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vstu.Eve-Ent
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: LYJJP2ZH5L
        TARGETED_DEVICE_FAMILY: 1
        TARGET_PATH: Sources/Eve-Ent
    prebuildScripts:
      - script: |
          mint run swiftgen swiftgen strings ${SCRIPT_INPUT_FILE_0} -t structured-swift4 --output ${SCRIPT_OUTPUT_FILE_0}
        name: L10nGen
        inputFiles:
          - ${TARGET_PATH}/Resources/Localizable.strings
        outputFiles:
          - ${TARGET_PATH}/Generated/L10n.swift
      - script: |
          mint run swiftgen swiftgen xcassets ${SCRIPT_INPUT_FILE_0} -t swift4 --output ${SCRIPT_OUTPUT_FILE_0}
        name: AssetsGen
        inputFiles:
          - ${TARGET_PATH}/Resources/Assets.xcassets
        outputFiles:
          - ${TARGET_PATH}/Generated/Assets.swift
    dependencies:
      - target: Domain
      - target: Data
      - target: Library
      - carthage: Overture
      - carthage: KeychainAccess
      - carthage: SDWebImage
      - carthage: Stevia
      - carthage: RouteComposer
      - sdk: CoreData.framework
    scheme:
      testTargets:
        - Eve-Ent-Tests
      gatherCoverageData: true

  Eve-Ent-Tests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    dependencies:
      - target: Eve-Ent
      - target: Domain
      - target: Library
      - target: Data
      - carthage: Overture
      - sdk: CoreData.framework
  
  Domain:
    type: framework
    platform: iOS
    sources:
      - path: Sources/Domain
    dependencies:
      - carthage: Overture
      - target: Library

  Data:
    type: framework
    platform: iOS
    sources:
      - path: Sources/Data
    dependencies:
      - target: Domain
      - target: Library
      - carthage: Overture
      - carthage: KeychainAccess
      - carthage: RouteComposer
      - sdk: CoreData.framework
    
  Library:
    type: framework
    platform: iOS
    sources:
      - path: Sources/Library
    dependencies:
      - sdk: CoreData.framework
      - carthage: KeychainAccess
      - carthage: Stevia